import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdir, rm, writeFile, readFile } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { addSectionCommand } from '../src/commands/add-section.js';
import { removeSectionCommand } from '../src/commands/remove-section.js';
import { createComponentCommand } from '../src/commands/create-component.js';
import { removeComponentCommand } from '../src/commands/remove-component.js';

describe('Feature Improvements', () => {
  const projectRoot = process.cwd();
  const testProjectRoot = path.join(projectRoot, 'temp-feature-test');
  const configDir = path.join(testProjectRoot, '.textor');
  const configPath = path.join(configDir, 'config.json');

  const originalCwd = process.cwd;

  beforeEach(async () => {
    process.cwd = () => testProjectRoot;
    if (existsSync(testProjectRoot)) await rm(testProjectRoot, { recursive: true, force: true });
    await mkdir(configDir, { recursive: true });
    
    const config = {
      paths: {
        pages: 'src/pages',
        features: 'src/features',
        components: 'src/components',
        layouts: 'src/layouts'
      },
      importAliases: {},
      naming: {
        routeExtension: '.astro',
        featureExtension: '.astro',
        componentExtension: '.astro',
        hookExtension: '.ts',
        testExtension: '.test.tsx'
      },
      signatures: {
        astro: '<!-- @generated by Textor -->',
        typescript: '// @generated by Textor'
      },
      features: {
        createSubComponentsDir: true,
        createScriptsDir: true,
        scriptsIndexFile: 'scripts/index.ts'
      },
      components: {
        createSubComponentsDir: false,
        createContext: true,
        createHook: true,
        createTests: true,
        createConfig: true,
        createConstants: true,
        createTypes: true
      }
    };
    await writeFile(configPath, JSON.stringify(config));
    await mkdir(path.join(testProjectRoot, 'src/pages'), { recursive: true });
    await mkdir(path.join(testProjectRoot, 'src/layouts'), { recursive: true });
  });

  afterEach(async () => {
    process.cwd = originalCwd;
    if (existsSync(testProjectRoot)) await rm(testProjectRoot, { recursive: true, force: true });
  });

  it('toPascalCase should respect camelCase in arguments', async () => {
    // This tests create-component which uses normalizeComponentName -> toPascalCase
    await createComponentCommand('myComponent', {});
    
    const componentPath = path.join(testProjectRoot, 'src/components/MyComponent/MyComponent.astro');
    expect(existsSync(componentPath), 'Component should be named MyComponent.astro').toBe(true);
  });

  it('add-section should respect camelCase in feature path', async () => {
    await addSectionCommand('/test', 'myFeature/mySubFeature', { layout: 'Main' });
    
    const featurePath = path.join(testProjectRoot, 'src/features/myFeature/mySubFeature/MyFeatureMySubFeature.astro');
    expect(existsSync(featurePath), 'Feature component should be named MyFeatureMySubFeature.astro').toBe(true);
  });

  it('add-section should inject script index inside the component', async () => {
    await addSectionCommand('/test', 'test-feature', { layout: 'Main' });
    
    const featurePath = path.join(testProjectRoot, 'src/features/test-feature/TestFeature.astro');
    const content = await readFile(featurePath, 'utf-8');
    
    expect(content).toContain('<script src="./scripts/index.ts"></script>');
  });

  it('remove-section should recursively delete feature directory with subdirectories', async () => {
    await addSectionCommand('/test', 'test-feature', { layout: 'Main' });
    const featureDirPath = path.join(testProjectRoot, 'src/features/test-feature');
    
    expect(existsSync(featureDirPath)).toBe(true);
    expect(existsSync(path.join(featureDirPath, 'scripts/index.ts'))).toBe(true);
    
    await removeSectionCommand('/test', null, {});
    
    expect(existsSync(featureDirPath)).toBe(false);
  });

  it('create-component should create sub-components subfolder and remove-component should delete it', async () => {
    // Enable createSubComponentsDir for this test explicitly just in case
    const configContent = await readFile(configPath, 'utf-8');
    const config = JSON.parse(configContent);
    config.components.createSubComponentsDir = true;
    await writeFile(configPath, JSON.stringify(config));

    await createComponentCommand('Button', {});
    const componentDirPath = path.join(testProjectRoot, 'src/components/Button');
    const subComponentsDirPath = path.join(componentDirPath, 'sub-components');

    expect(existsSync(componentDirPath)).toBe(true);
    expect(existsSync(subComponentsDirPath)).toBe(true);

    await removeComponentCommand('Button', {});
    expect(existsSync(componentDirPath)).toBe(false);
  });
});
