import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdir, rm, writeFile, readFile } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { addSectionCommand } from '../src/commands/add-section.js';

const TEST_DIR = path.join(process.cwd(), 'temp-templates-test');

describe('Valid TS Templates', () => {
  const originalCwd = process.cwd;

  beforeEach(async () => {
    process.cwd = () => TEST_DIR;
    if (existsSync(TEST_DIR)) {
      await rm(TEST_DIR, { recursive: true, force: true });
    }
    await mkdir(path.join(TEST_DIR, '.textor/templates'), { recursive: true });
    
    const config = {
      configVersion: 2,
      paths: {
        pages: 'src/pages',
        features: 'src/features',
        components: 'src/components',
        layouts: 'src/layouts'
      },
      naming: {
        routeExtension: '.astro',
        featureExtension: '.ts',
        componentExtension: '.tsx',
        hookExtension: '.ts',
        testExtension: '.test.tsx'
      },
      signatures: {
        astro: '<!-- @generated by Textor -->',
        typescript: '// @generated by Textor'
      },
      features: {
        framework: 'react',
        entry: 'pascal'
      },
      components: {
        framework: 'react'
      }
    };
    await writeFile(path.join(TEST_DIR, '.textor/config.json'), JSON.stringify(config));
  });

  afterEach(async () => {
    process.cwd = originalCwd;
    if (existsSync(TEST_DIR)) {
      await rm(TEST_DIR, { recursive: true, force: true });
    }
  });

  it('should support __variable__ and name variations in templates', async () => {
    const templateContent = `/**
 * @generated by Textor
 * Feature: {{componentName}}
 */
export const __componentName__Route = {
  name: '__componentNameCamel__',
  path: '/__componentNameKebab__',
  id: '__componentNameUpper__'
};
`;
    await writeFile(path.join(TEST_DIR, '.textor/templates/feature.ts'), templateContent);

    await addSectionCommand('/test', 'user-profile', {});

    const featurePath = path.join(TEST_DIR, 'src/features/user-profile/UserProfile.ts');
    expect(existsSync(featurePath)).toBe(true);
    
    const content = await readFile(featurePath, 'utf-8');
    expect(content).toContain('Feature: UserProfile');
    expect(content).toContain('export const UserProfileRoute = {');
    expect(content).toContain("name: 'userProfile',");
    expect(content).toContain("path: '/user-profile',");
    expect(content).toContain("id: 'USER_PROFILE'");
  });
});
